import { Inter } from 'next/font/google'
import './globals.css'
import NextAuthProvider from './providers'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)
  console.log(
    '🚀 ~ file: layout.js:14 ~ RootLayout ~ session:',
    session?.user?.email
  )

  if(session?.user?.email) {
    
  }

  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  )
}
